### PR TITLE
feat(YouTube/Shorts overlay buttons) Add `Shorts overlay buttons` patch

### PR DESCRIPTION
**Pull request by anddea**
Fine-tuned and refined Shorts Buttons

- Renamed Shorts outline button patch to Shorts overlay buttons patch
- Multiple options now available (selectable in patches.json):
-- Default - buttons like in TikTok (which are better than YouTube's), buttons are not available on older versions or with app version spoofing patch
-- Outline - outline buttons, available for older versions
-- OutlineCircle - rounded outline buttons inside circle, for older versions Outline buttons used

- Main buttons are in xxhdpi folder, only specific buttons kept in other dpi folders (from what I can tell there's no need duplicating main buttons but if you face issues tell me)
- Some WebP icons are 960x960 (higher quality + to make it more easy to scale for different dpis if needed)
- Replaced Share, Like On, Dislike On buttons for Shorts Outline buttons

What I'd like to change also: imo, buttons are too spread from each other but I couldn't figure out how to change padding between them for new YouTube versions

Edit: reduced code but didn't have time to test it yet. Probably won't reduce it any further.

Edit 2: Reduced code works as expected for me, if you face issues let me know.

<details>
<summary>Screenshots</summary>

### Default (I have bigger buttons, but with these paddings between icons, they look not so good)
s1

### OutlineCircle (even though they may seem small, they're actually full width and full height, so only changing YouTube layout code will change height and width)
s2

### Outline 
s3

</details>

### CODE REVIEW

**Comment by YT-Advanced** [comment]
Any screenshot of the Outline Circle button please

**Comment by anddea** [comment]
> Any screenshot of the Outline Circle button please

Attached to original post

**Comment by YT-Advanced** [comment]
I will remove the Tiktok variant, and redo all these changes

**Comment by anddea** [comment]
> I will remove the Tiktok variant

Why?

**Comment by YT-Advanced** [comment]
The like/dislike became love/broken heart button, which is not match

**Comment by anddea** [comment]
> The like/dislike became love/broken heart button, which is not match

I see. I used it because TikTok has these icons instead of like/dislike but has the same purpose, and I'm not sure what to do to match design for like and dislike buttons.  I crowdsourced opinion on my designer forum and it was by far most favorite option, so consider keeping it as an option, so people decide for themselves. After all no one is stopping people for using Outline buttons instead.

**Comment by anddea** [comment]
If you'll be able to figure out how to change paddlings between buttons and also add speed button, that woold be great.

**Pull request closed without merging**
